---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summer-k8s-app
  template:
    metadata:
      labels:
        app: summer-k8s-app
    spec:
      containers:
      - name: webserver-simple
        image: kostiscodefresh/summer-of-k8s-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
